server:
  port: 8080
spring:
  data:
    mongodb:
      uri: ADD YOUR MONGODB CONN STRING HERE
      database: yaba
logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    ca.architech: DEBUG
